name: Feature Cicd Development

on:
  push:
    branches:
      - 'feature/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: runtest
        run: echo "Running on feature branch"

      - name: deploy
        run: echo "deploying on the feature branch"
